version: '3.8'

services:
  food-tracker-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    restart: unless-stopped 